

repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8
        args: # arguments to configure flake8
            # making isort line length compatible with black
          - "--max-line-length=119"
          - "--ignore=E203, E402, E501, W503, F403"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        pass_filenames: false
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort